import { Ibairro } from '../../interfaces/ibairro/ibairro';

export class Bairro {

  getListaBairro(): Ibairro[] {

    const lista = [
      { bairro: 'Saúde', RA: 'I RA', AP: 'AP 01', RP: 'RP 1.0', SV: 'SF01' },
      { bairro: 'Gamboa', RA: 'I RA', AP: 'AP 01', RP: 'RP 1.0', SV: 'SF01' },
      { bairro: 'Santo Cristo', RA: 'I RA', AP: 'AP 01', RP: 'RP 1.0', SV: 'SF01' },
      { bairro: 'Caju', RA: 'I RA', AP: 'AP 01', RP: 'RP 1.0', SV: 'SF01' },
      { bairro: 'Centro', RA: 'II RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Catumbi', RA: 'III RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Rio Comprido', RA: 'III RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Cidade Nova', RA: 'III RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Estácio', RA: 'III RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Imperial de São Cristóvão', RA: 'VII RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Mangueira', RA: 'VII RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Benfica ', RA: 'VII RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Paquetá', RA: 'XXI RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Santa Teresa', RA: 'XXIII RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Flamengo', RA: 'IV RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Glória', RA: 'IV RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Laranjeiras', RA: 'IV RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Catete', RA: 'IV RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Cosme Velho', RA: 'IV RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Botafogo', RA: 'IV RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Humaitá', RA: 'IV RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Urca', RA: 'IV RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Leme', RA: 'V RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Copacabana', RA: 'V RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Ipanema', RA: 'VI RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Arpoador', RA: 'VI RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Leblon', RA: 'VI RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Lagoa', RA: 'VI RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Jardim Botânico', RA: 'VI RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Gávea', RA: 'VI RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Vidigal', RA: 'VI RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'São Conrado', RA: 'VI RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Praça da Bandeira', RA: 'VIII RA', AP: 'AP 02', RP: 'RP 2.2', SV: 'SF01' },
      { bairro: 'Tijuca', RA: 'VIII RA', AP: 'AP 02', RP: 'RP 2.2', SV: 'SF01' },
      { bairro: 'Alto da Boa Vista', RA: 'VIII RA', AP: 'AP 02', RP: 'RP 2.2', SV: 'SF01' },
      { bairro: 'Maracanã', RA: 'IX RA ', AP: 'AP 02', RP: 'RP 2.2', SV: 'SF01' },
      { bairro: 'Vila Isabel', RA: 'IX RA ', AP: 'AP 02', RP: 'RP 2.2', SV: 'SF01' },
      { bairro: 'Andaraí', RA: 'IX RA ', AP: 'AP 02', RP: 'RP 2.2', SV: 'SF01' },
      { bairro: 'Grajaú', RA: 'IX RA ', AP: 'AP 02', RP: 'RP 2.2', SV: 'SF01' },
      { bairro: 'Manguinhos', RA: 'X RA ', AP: 'AP 03', RP: 'RP 3.1', SV: 'SF03' },
      { bairro: 'Bonsucesso', RA: 'X RA ', AP: 'AP 03', RP: 'RP 3.1', SV: 'SF03' },
      { bairro: 'Ramos', RA: 'X RA ', AP: 'AP 03', RP: 'RP 3.1', SV: 'SF03' },
      { bairro: 'Olaria', RA: 'X RA ', AP: 'AP 03', RP: 'RP 3.1', SV: 'SF03' },
      { bairro: 'Penha', RA: 'XI RA', AP: 'AP 03', RP: 'RP 3.5', SV: 'SF03' },
      { bairro: 'Penha Circular', RA: 'XI RA', AP: 'AP 03', RP: 'RP 3.5', SV: 'SF03' },
      { bairro: 'Braz de Pina', RA: 'XI RA', AP: 'AP 03', RP: 'RP 3.5', SV: 'SF03' },
      { bairro: 'Cordovil', RA: 'XXXI RA', AP: 'AP 03', RP: 'RP 3.5', SV: 'SF03' },
      { bairro: 'Parada de Lucas', RA: 'XXXI RA', AP: 'AP 03', RP: 'RP 3.5', SV: 'SF03' },
      { bairro: 'Vigário Geral', RA: 'XXXI RA', AP: 'AP 03', RP: 'RP 3.5', SV: 'SF03' },
      { bairro: 'Jardim América', RA: 'XXXI RA', AP: 'AP 03', RP: 'RP 3.5', SV: 'SF03' },
      { bairro: 'Higienópolis', RA: 'XII RA', AP: 'AP 03', RP: 'RP 3.4', SV: 'SF03' },
      { bairro: 'Jacaré', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Maria da Graça', RA: 'XII RA', AP: 'AP 03', RP: 'RP 3.4', SV: 'SF03' },
      { bairro: 'Del Castilho', RA: 'XII RA', AP: 'AP 03', RP: 'RP 3.4', SV: 'SF03' },
      { bairro: 'Inhaúma', RA: 'XII RA', AP: 'AP 03', RP: 'RP 3.4', SV: 'SF03' },
      { bairro: 'Engenho da Rainha', RA: 'XII RA', AP: 'AP 03', RP: 'RP 3.4', SV: 'SF03' },
      { bairro: 'Tomás Coelho', RA: 'XII RA', AP: 'AP 03', RP: 'RP 3.4', SV: 'SF03' },
      { bairro: 'São Francisco Xavier', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Rocha', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Riachuelo', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Sampaio', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Engenho Novo', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Lins de Vasconcelos', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Méier', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Todos os Santos', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Cachambi', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Engenho de Dentro', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Água Santa', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Encantado', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Piedade', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Abolição', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Pilares', RA: 'XIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Vila Kosmos', RA: 'XIV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Vicente de Carvalho', RA: 'XIV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Vila da Penha', RA: 'XIV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Vista Alegre', RA: 'XIV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Irajá', RA: 'XIV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Colégio', RA: 'XIV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Campinho', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Quintino Bocaiúva', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Cavalcanti', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Engenheiro Leal', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Cascadura', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Madureira', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Vaz Lobo', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Turiaçu', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Rocha Miranda', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Honório Gurgel', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Oswaldo Cruz', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Bento Ribeiro', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Marechal Hermes', RA: 'XV RA', AP: 'AP 03', RP: 'RP 3.3', SV: 'SF03' },
      { bairro: 'Ribeira', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Zumbi', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Cacuia', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Pitangueiras', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Praia da Bandeira', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Cocotá', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Ilha do Goverandor', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Bancários', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Freguesia', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Jardim Guanabara', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Jardim Carioca', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Tauá', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Moneró', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Portuguesa', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Galeão', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Cidade Universitária', RA: ' XX RA', AP: 'AP 03', RP: 'RP 3.7', SV: 'SF03' },
      { bairro: 'Guadalupe', RA: 'XXII RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Anchieta', RA: 'XXII RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Parque Anchieta', RA: 'XXII RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Ricardo de Albuquerque', RA: 'XXII RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Coelho Neto', RA: 'XXV RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Acari', RA: 'XXV RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Barros Filho', RA: 'XXV RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Costa Barros', RA: 'XXV RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Pavuna', RA: 'XXV RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Jacarepaguá', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Anil', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Gardênia Azul', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Cidade de Deus', RA: 'XXXIV RA ', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Curicica', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Freguesia (Jacarepaguá)', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Pechincha', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Taquara', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Tanque', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Praça Seca', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Vila Valqueire', RA: 'XVI RA', AP: 'AP 04', RP: 'RP 4.1', SV: 'SF05' },
      { bairro: 'Joá', RA: 'XXIV RA', AP: 'AP 04', RP: 'RP 4.2', SV: 'SF05' },
      { bairro: 'Itanhangá', RA: 'XXIV RA', AP: 'AP 04', RP: 'RP 4.2', SV: 'SF05' },
      { bairro: 'Barra da Tijuca', RA: 'XXIV RA', AP: 'AP 04', RP: 'RP 4.2', SV: 'SF05' },
      { bairro: 'Camorim', RA: 'XXIV RA', AP: 'AP 04', RP: 'RP 4.2', SV: 'SF05' },
      { bairro: 'Vargem Pequena', RA: 'XXIV RA', AP: 'AP 04', RP: 'RP 4.2', SV: 'SF05' },
      { bairro: 'Vargem Grande', RA: 'XXIV RA', AP: 'AP 04', RP: 'RP 4.2', SV: 'SF05' },
      { bairro: 'Recreio dos Bandeirantes', RA: 'XXIV RA', AP: 'AP 04', RP: 'RP 4.2', SV: 'SF05' },
      { bairro: 'Grumari', RA: 'XXIV RA', AP: 'AP 04', RP: 'RP 4.2', SV: 'SF05' },
      { bairro: 'Deodoro', RA: 'XXXIII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Vila Militar', RA: 'XXXIII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Campo dos Afonsos', RA: 'XXXIII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Jardim Sulacap', RA: 'XXXIII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Magalhães Bastos', RA: 'XXXIII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Realengo', RA: 'XXXIII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Padre Miguel', RA: 'XVII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Bangu', RA: 'XVII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Senador Camará', RA: 'XVII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Santíssimo', RA: 'XVIII RA', AP: 'AP 05', RP: 'RP 5.2', SV: 'SF04' },
      { bairro: 'Campo Grande', RA: 'XVIII RA', AP: 'AP 05', RP: 'RP 5.2', SV: 'SF04' },
      { bairro: 'Senador Vasconcelos', RA: 'XVIII RA', AP: 'AP 05', RP: 'RP 5.2', SV: 'SF04' },
      { bairro: 'Inhoaíba', RA: 'XVIII RA', AP: 'AP 05', RP: 'RP 5.2', SV: 'SF04' },
      { bairro: 'Cosmos', RA: 'XVIII RA', AP: 'AP 05', RP: 'RP 5.2', SV: 'SF04' },
      { bairro: 'Paciência', RA: 'XIX RA', AP: 'AP 05', RP: 'RP 5.3', SV: 'SF04' },
      { bairro: 'Santa Cruz', RA: 'XIX RA', AP: 'AP 05', RP: 'RP 5.3', SV: 'SF04' },
      { bairro: 'Sepetiba', RA: 'XIX RA', AP: 'AP 05', RP: 'RP 5.3', SV: 'SF04' },
      { bairro: 'Guaratiba', RA: 'XXVI RA ', AP: 'AP 05', RP: 'RP 5.4', SV: 'SF04' },
      { bairro: 'Barra de Guaratiba', RA: 'XXVI RA ', AP: 'AP 05', RP: 'RP 5.4', SV: 'SF04' },
      { bairro: 'Pedra de Guaratiba', RA: 'XXVI RA ', AP: 'AP 05', RP: 'RP 5.4', SV: 'SF04' },
      { bairro: 'Rocinha', RA: 'XXVII RA', AP: 'AP 02', RP: 'RP 2.1', SV: 'SF02' },
      { bairro: 'Jacarezinho', RA: 'XXVIII RA', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Complexo do Alemão', RA: 'XXIX RA', AP: 'AP 03', RP: 'RP 3.4', SV: 'SF03' },
      { bairro: 'Maré', RA: 'XXX RA ', AP: 'AP 03', RP: 'RP 3.2', SV: 'SF03' },
      { bairro: 'Vasco da Gama', RA: 'VII RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Parque Colúmbia ', RA: 'XXV RA', AP: 'AP 03', RP: 'RP 3.6', SV: 'SF03' },
      { bairro: 'Gericinó', RA: 'XVII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' },
      { bairro: 'Lapa', RA: 'II RA', AP: 'AP 01', RP: 'RP 1.1', SV: 'SF01' },
      { bairro: 'Vila Kennedy', RA: 'XVII RA', AP: 'AP 05', RP: 'RP 5.1', SV: 'SF04' }
    ];

    return lista.sort((a, b) => (a.bairro > b.bairro) ? 1 : -1);
  }
}
